
theme: jekyll-theme-dinky
title: C'est le titre
description: C'est la description
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'this a the second page', 'pagename': 'page1'},
{'name': 'Go there', 'pagename': 'page2'},
{'name': 'Yet Another page', 'pagename': 'page3'},
]
