
theme: jekyll-theme-slate
title: C'est le titre
description: C'est la description
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Cheat Sheet', 'pagename': 'cheatsheet'},
{'name': 'Resources', 'pagename': 'resources'},
{'name': 'About us', 'pagename': 'about'},
]
