theme: jekyll-theme-dinky
title: Africa Rising is here
description: A rapid description of the website content
menu: [
{'name': 'Introduction', 'pagename': 'index'},
{'name': 'Data collectionn', 'pagename': 'data collection'},
]
